# DEPRECATED: Este workflow está obsoleto. Usa build-and-test.yml en su lugar.
# Se mantiene para referencia histórica.

name: Build IO (DEPRECATED)

# Controls when the workflow will run (solo manual)
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-IO:
    name: Build IO
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build EjemploPrintf.c
        run: |
          cd IO
          gcc -c EjemploPrintf.c
          gcc -o EjemploPrintf.exe EjemploPrintf.o
          ./EjemploPrintf.exe
          
          
